from django.urls import path

from .views import (
    ActionCenterView,
    AgentFeedbackDetailView,
    AgentFeedbackListView,
    AgentsListView,
    AnalyticsOverviewView,
    AuditDetailView,
    AuditsListView,
    CaseTypeDetailView,
    CaseTypesListView,
    CoachingDetailView,
    CoachingListView,
    EvaluationDayOffView,
    EvaluationProgressView,
    EvaluationScheduledDayOffView,
    ExternalStatusView,
    ManagedUserDetailView,
    ManagedUsersListView,
    MonitoringDetailView,
    MonitoringListView,
    PowerAutomateStatusView,
    PowerAutomateTriggerView,
    ProductionListView,
    RankingsView,
    ReportsView,
    RolePermissionsView,
    SupervisorRequestDetailView,
    SupervisorRequestReplyView,
    SupervisorRequestsListView,
    TeamMetricDetailView,
    TeamMetricsListView,
    TeamTrackingListView,
)

urlpatterns = [
    path("external/status/", ExternalStatusView.as_view(), name="external-status"),
    path("agents/", AgentsListView.as_view(), name="agents-list"),
    path("audits/", AuditsListView.as_view(), name="audits-list"),
    path("audits/<str:audit_id>/", AuditDetailView.as_view(), name="audits-detail"),
    path("case-types/", CaseTypesListView.as_view(), name="case-types-list"),
    path("case-types/<str:case_id>/", CaseTypeDetailView.as_view(), name="case-types-detail"),
    path("metrics/", TeamMetricsListView.as_view(), name="team-metrics-list"),
    path("metrics/<str:metric_id>/", TeamMetricDetailView.as_view(), name="team-metrics-detail"),
    path("monitoring/", MonitoringListView.as_view(), name="monitoring-list"),
    path("monitoring/<str:item_id>/", MonitoringDetailView.as_view(), name="monitoring-detail"),
    path("production/", ProductionListView.as_view(), name="production-list"),
    path("agent-feedback/", AgentFeedbackListView.as_view(), name="agent-feedback-list"),
    path(
        "agent-feedback/<str:item_id>/",
        AgentFeedbackDetailView.as_view(),
        name="agent-feedback-detail",
    ),
    path(
        "supervisor-requests/",
        SupervisorRequestsListView.as_view(),
        name="supervisor-requests-list",
    ),
    path(
        "supervisor-requests/<str:item_id>/",
        SupervisorRequestDetailView.as_view(),
        name="supervisor-requests-detail",
    ),
    path(
        "supervisor-requests/<str:item_id>/replies/",
        SupervisorRequestReplyView.as_view(),
        name="supervisor-requests-replies",
    ),
    path("coaching/", CoachingListView.as_view(), name="coaching-list"),
    path("coaching/<str:item_id>/", CoachingDetailView.as_view(), name="coaching-detail"),
    path("team-tracking/", TeamTrackingListView.as_view(), name="team-tracking-list"),
    path("managed-users/", ManagedUsersListView.as_view(), name="managed-users-list"),
    path(
        "managed-users/<str:user_id>/",
        ManagedUserDetailView.as_view(),
        name="managed-users-detail",
    ),
    path("role-permissions/", RolePermissionsView.as_view(), name="role-permissions"),
    path(
        "integrations/power-automate/",
        PowerAutomateStatusView.as_view(),
        name="power-automate-status",
    ),
    path(
        "integrations/power-automate/<str:flow>/",
        PowerAutomateTriggerView.as_view(),
        name="power-automate-trigger",
    ),
    path("analytics/", AnalyticsOverviewView.as_view(), name="analytics-overview"),
    path("rankings/", RankingsView.as_view(), name="rankings"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("action-center/", ActionCenterView.as_view(), name="action-center"),
    path(
        "evaluation-progress/",
        EvaluationProgressView.as_view(),
        name="evaluation-progress",
    ),
    path(
        "evaluation-progress/day-off/",
        EvaluationDayOffView.as_view(),
        name="evaluation-progress-day-off",
    ),
    path(
        "evaluation-progress/scheduled-day-off/",
        EvaluationScheduledDayOffView.as_view(),
        name="evaluation-progress-scheduled-day-off",
    ),
]
